file: /administration/configuration
description: |
  Outlines common MongoDB configurations and examples of best-practice
  configurations for common use cases.
---
file: /tutorial/upgrade-revision
description: |
  Introduces the basic process for upgrading a MongoDB deployment
  between different minor release versions.
---
file: /tutorial/manage-mongodb-processes
description: |
  Start, configure, and manage running :program:`mongod` process.
---
file: /tutorial/rotate-log-files
description: |
  Archive the current log files and start new ones.
---
file: /data-center-awareness
description: |
  Presents the MongoDB features that allow application developers and
  database administrators to configure their deployments to be more
  data center aware or allow operational and location-based
  separation.
...
